//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libros()
        {
            this.prestamos = new HashSet<prestamos>();
        }
    
        public int idLibro { get; set; }
        public string isbn { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public string editorial { get; set; }
        public string edicion { get; set; }
        public int numeroEdicion { get; set; }
        public string pais { get; set; }
        public string idioma { get; set; }
        public string materia { get; set; }
        public int numeroPaginas { get; set; }
        public string ubicacion { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamos> prestamos { get; set; }
    }
}
