//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamos
    {
        public int idPrestamo { get; set; }
        public int idUsuario { get; set; }
        public int idLibro { get; set; }
        public System.DateTime fechaPrestamo { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
        public bool estado { get; set; }
    
        public virtual libros libros { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
